spring:
  datasource:
    name: test
    url: jdbc:mysql://192.168.40.150:3306/test?serverTimezone=UTC
    username: root
    password: root
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
